### PR TITLE
Link warnings.

### PR DESCRIPTION
**Pull request by sasuke200**
Helps prevent phishing or fake links by warning the user!

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
Did you really need to include `System.Text.RegularExpressions`? I looked through the commit and don't see anything that requires it.

**Comment by sasuke200** [comment]
No i did not need to add that, removed it and fixed it so dddhttp://google.com would still alert.

**Comment by waylaidwanderer** [comment]
One more thing - isLink doesn't have to be global, I think. It should work fine as a local variable, no?

**Comment by sasuke200** [comment]
It will work fine, changed.

**Comment by waylaidwanderer** [comment]
Alright, looks good then.

**Pull request merged**
